version: "3"

services:
  directus:
    image: directus/directus:11.0.2
    networks:
      - backend
    ports:
      - 8055:8055
    volumes:
      - ./directus/directus/database:/directus/database
      - ./directus/directus/uploads:/directus/uploads
      - ./directus/directus/extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"

      WEBSOCKETS_ENABLED: "true"

      CORS_ENABLED: "true" # for development
      CORS_ORIGIN: "*" # for development

  web:
    build: ./web
    networks:
      - backend
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync+restart
          path: ./web
          target: /app

networks:
  backend:
